#!/bin/bash

python3 -m pip install tqdm matplotlib                                    # Install dependencies
python3 -m pip install -i https://test.pypi.org/simple/ comptester==0.2.0 # Install comptester
